[versions]
kotlin = "2.2.20"
picocli = "4.7.7"
junit = "5.13.4"
assertj = "3.27.3"
spotless = "7.2.1"
ktlint = "1.7.1"
graalvm-buildtools = "0.10.6"
maven-publish = "0.34.0"
shadow = "8.3.6"
spring-boot = "3.5.5"

[libraries]
graalvm-nativeimage = { module = "org.graalvm.sdk:nativeimage", version = "24.2.0" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-context = { module = "org.springframework:spring-context" }
slf4j-api = { module = "org.slf4j:slf4j-api" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-buildtools" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
